# Generated by Django 2.2.2 on 2019-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='module',
            field=models.CharField(choices=[('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], max_length=10, verbose_name='Module type'),
        ),
        migrations.AlterField(
            model_name='codedlabel',
            name='group',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], max_length=5),
        ),
    ]
