# Generated by Django 2.2.2 on 2019-07-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0002_auto_20190717_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='import_domain_area',
            new_name='domain_area_terms',
        ),
    ]
