# Generated by Django 2.2.2 on 2019-06-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0002_auto_20190624_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='casestudy',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
