# Generated by Django 2.2.2 on 2019-06-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0003_auto_20190624_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('casestudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CaseStudy')),
            ],
        ),
    ]
