# Generated by Django 2.2.2 on 2019-06-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0004_casestudylayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudylayer',
            name='casestudy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='tools4msp.CaseStudy'),
        ),
        migrations.CreateModel(
            name='CaseStudyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('casestudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='tools4msp.CaseStudy')),
            ],
        ),
    ]
