# Generated by Django 2.2.2 on 2019-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0005_auto_20190626_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='grid_resolution',
            new_name='resolution',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='cstype',
            field=models.CharField(choices=[('default', 'Default run'), ('customize', 'Customize run')], default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudy',
            name='module',
            field=models.CharField(choices=[('cea', 'CEA'), ('musc', 'MUSC'), ('partrac', 'Particle tracking')], default='cea', max_length=10),
            preserve_default=False,
        ),
    ]
