# Generated by Django 2.2.2 on 2019-09-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0005_auto_20190916_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudyrungraphic',
            old_name='casestudy',
            new_name='casestudyrun',
        ),
    ]
