# Generated by Django 2.2.2 on 2019-07-03 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools4msp', '0006_auto_20190703_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='tools4msp',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='cstype',
            field=models.CharField(choices=[('default', 'Default run'), ('customize', 'Customize run')], max_length=10, verbose_name='CS Type'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='module',
            field=models.CharField(choices=[('cea', 'CEA'), ('musc', 'MUSC'), ('partrac', 'Particle tracking')], max_length=10, verbose_name='Module type'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='resolution',
            field=models.FloatField(default=1000, help_text='resoution of analysis (meters)'),
        ),
    ]
