# Generated by Django 2.2.2 on 2019-09-17 13:53

from django.db import migrations, models
import django.db.models.deletion
import tools4msp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0006_auto_20190916_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudygraphic',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudyinput',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudylayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudyrungraphic',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudyruninput',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudyrunlayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudyrunoutput',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AddField(
            model_name='casestudyrunoutputlayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='casestudyrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='tools4msp.CaseStudyRun'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutputlayer',
            name='casestudyrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputlayers', to='tools4msp.CaseStudyRun'),
        ),
    ]
