# Generated by Django 2.2.2 on 2019-09-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0007_auto_20190917_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudyrungraphic',
            name='casestudyrun',
        ),
        migrations.RemoveField(
            model_name='casestudyrungraphic',
            name='coded_label',
        ),
        migrations.DeleteModel(
            name='CaseStudyGraphic',
        ),
        migrations.DeleteModel(
            name='CaseStudyRunGraphic',
        ),
    ]
