# Generated by Django 2.2.2 on 2019-07-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0007_auto_20190703_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudy',
            old_name='area_of_interest',
            new_name='domain_area',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tool_ci',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tool_coexist',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='tool_mes',
        ),
    ]
