# Generated by Django 2.2.2 on 2019-09-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0008_auto_20190917_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudyinput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudylayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyruninput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunlayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutputlayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
    ]
