# Generated by Django 2.2.2 on 2019-07-04 20:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tools4msp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0009_auto_20190703_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudylayer',
            name='layer',
            field=models.FileField(blank=True, null=True, upload_to=tools4msp.models.generate_layer_filename),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='domain_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='polygon geometry(Lat Log WGS84)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='domain_area_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CaseStudyGrid', verbose_name='Domain area (source dataset)'),
        ),
    ]
