# Generated by Django 2.2.2 on 2019-10-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0009_auto_20190919_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='MUCscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.Context')),
                ('use1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mucscore_use1', to='tools4msp.Use')),
                ('use2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mucscore_use2', to='tools4msp.Use')),
            ],
            options={
                'unique_together': {('use1', 'use2')},
            },
        ),
    ]
