# Generated by Django 2.2.2 on 2019-10-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0010_mucscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MUCscore',
            new_name='MUCPotentialScore',
        ),
    ]
