# Generated by Django 2.2.2 on 2019-07-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0010_auto_20190704_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudyinput',
            name='name',
        ),
        migrations.AddField(
            model_name='casestudyinput',
            name='input_type',
            field=models.CharField(choices=[('pres_weights', 'Pressure weights'), ('sensitivities', 'Sensitivities'), ('muc_scores', 'MUC scores')], default='aaa', max_length=15),
            preserve_default=False,
        ),
    ]
