# Generated by Django 2.2.2 on 2019-10-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0011_auto_20191008_0617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MUCPotentialScore',
            new_name='MUCPotentialConflict',
        ),
    ]
