# Generated by Django 2.2.2 on 2019-07-09 07:02

from django.db import migrations, models
import django.utils.timezone
import tools4msp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0011_auto_20190709_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudylayer',
            old_name='layer',
            new_name='layerfile',
        ),
        migrations.AddField(
            model_name='casestudyinput',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudyinput',
            name='inputfile',
            field=models.FileField(blank=True, null=True, upload_to=tools4msp.models.generate_input_filename),
        ),
        migrations.AddField(
            model_name='casestudyinput',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='casestudylayer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudylayer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
