# Generated by Django 2.2.2 on 2019-07-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0012_auto_20190709_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudylayer',
            name='name',
        ),
        migrations.AddField(
            model_name='casestudylayer',
            name='layer_type',
            field=models.CharField(default='grid', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='env',
            name='code',
            field=models.CharField(default='todo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='code',
            field=models.CharField(default='todo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='use',
            name='code',
            field=models.CharField(default='todo', max_length=10),
            preserve_default=False,
        ),
    ]
