# Generated by Django 2.2.2 on 2019-10-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0012_auto_20191008_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='mucpotentialconflict',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
