# Generated by Django 2.2.2 on 2019-10-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0013_mucpotentialconflict_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedlabel',
            name='code',
            field=models.SlugField(max_length=15, unique=True),
        ),
    ]
