# Generated by Django 2.2.2 on 2019-07-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0013_auto_20190709_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodedLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cltype', models.CharField(choices=[('grid', 'Grid'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure')], max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='casestudylayer',
            name='layer_type',
            field=models.ForeignKey(limit_choices_to={'cltype__in': ['grid', 'pres', 'env', 'use']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure')], max_length=5),
        ),
    ]
