# Generated by Django 2.2.2 on 2019-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0015_auto_20190709_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msfdenv',
            name='broad_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msfdenv',
            name='ecosystem_element',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msfdenv',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='msfdpres',
            name='msfd_pressure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msfdpres',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='msfduse',
            name='activity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='msfduse',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
