# Generated by Django 2.2.2 on 2019-07-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0016_auto_20190709_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedlabel',
            name='old_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casestudyinput',
            name='input_type',
            field=models.CharField(choices=[('pre_weights', 'Pressure weights'), ('sensitivities', 'Sensitivities'), ('muc_scores', 'MUC scores')], max_length=15),
        ),
        migrations.AlterField(
            model_name='casestudylayer',
            name='layer_type',
            field=models.ForeignKey(limit_choices_to={'cltype__in': ['grid', 'pre', 'env', 'use']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
    ]
