# Generated by Django 2.2.2 on 2019-10-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0016_partracdata_partracscenario_partractime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partracdata',
            name='particle_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
