# Generated by Django 2.2.2 on 2019-07-11 12:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0017_auto_20190710_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='polygon geometry(Lat Log WGS84)', null=True, srid=4326)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
