# Generated by Django 2.2.2 on 2019-10-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0017_auto_20191010_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='partracdata',
            name='grid_columnx',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='partracdata',
            name='grid_rowy',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
