# Generated by Django 2.2.2 on 2019-07-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0018_domainarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='import_domain_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.DomainArea'),
        ),
    ]
