# Generated by Django 2.2.3 on 2019-12-18 09:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0018_auto_20191017_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartracGrid',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('filename', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='partracdata',
            name='geo',
            field=django.contrib.gis.db.models.fields.PointField(help_text='point geometry', srid=3035),
        ),
    ]
