# Generated by Django 2.2.3 on 2019-12-18 09:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0019_auto_20191218_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partracgrid',
            name='rast',
            field=django.contrib.gis.db.models.fields.RasterField(srid=3035),
        ),
    ]
