# Generated by Django 2.2.2 on 2019-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0020_auto_20190711_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='import_domain_area',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='import_domain_area',
            field=models.ManyToManyField(to='tools4msp.DomainArea'),
        ),
    ]
