# Generated by Django 2.2.2 on 2019-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0021_auto_20190711_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='import_domain_area',
            field=models.ManyToManyField(blank=True, null=True, to='tools4msp.DomainArea'),
        ),
    ]
