# Generated by Django 2.2.2 on 2019-07-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0023_auto_20190713_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyLabel',
            fields=[
                ('codedlabel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tools4msp.CodedLabel')),
            ],
            options={
                'ordering': ['label'],
            },
            bases=('tools4msp.codedlabel',),
        ),
        migrations.AlterModelOptions(
            name='codedlabel',
            options={'ordering': ['cltype', 'label']},
        ),
    ]
