# Generated by Django 2.2.3 on 2020-06-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0023_auto_20200423_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='cstype',
            field=models.CharField(choices=[('default', 'Default run'), ('customized', 'Customized run')], max_length=10, verbose_name='CS Type'),
        ),
        migrations.AlterField(
            model_name='casestudyinput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudylayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyruninput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunlayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutputlayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='codedlabel',
            name='group',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('usepre', 'Use-Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('usepre', 'Use-Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], max_length=5),
        ),
    ]
