# Generated by Django 2.2.13 on 2020-06-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0024_auto_20200617_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-cstype', 'created'], 'permissions': (('download_casestudy', 'Download case study'), ('run_casestudy', 'Run case study')), 'verbose_name_plural': 'Case studies'},
        ),
        migrations.CreateModel(
            name='PartracDataGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_columnx', models.IntegerField(blank=True, db_index=True, null=True)),
                ('grid_rowy', models.IntegerField(blank=True, db_index=True, null=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.PartracGrid')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.PartracScenario')),
            ],
        ),
    ]
