# Generated by Django 2.2.2 on 2019-07-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0024_auto_20190713_2043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseStudyLabel',
            new_name='Grid',
        ),
    ]
