# Generated by Django 2.2.2 on 2019-07-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0025_auto_20190713_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grid',
        ),
    ]
