# Generated by Django 2.2.13 on 2020-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0026_auto_20200713_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
