# Generated by Django 2.2.3 on 2019-07-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0026_delete_grid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudylayer',
            options={'ordering': ['layer_type__cltype']},
        ),
    ]
