# Generated by Django 3.2.9 on 2021-12-13 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0027_casestudy_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='cstype',
            field=models.CharField(choices=[('default', 'Default run'), ('customized', 'Customized run')], help_text='CaseStudy type. Accepted values are: default, customized', max_length=10, verbose_name='CS Type'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.CharField(blank=True, help_text='CaseStudy description', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='domain_area',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='GeoJSON rapresentation of the CaseStudy domain area (MultiPolygon Lat Log WGS84)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='domain_area_terms',
            field=models.ManyToManyField(blank=True, help_text='Domain area term. See DomainAreas thesaurus', to='tools4msp.DomainArea'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='label',
            field=models.CharField(help_text='CaseStudy title', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='module',
            field=models.CharField(choices=[('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], help_text='Module type. Accepted values are: cea, muc, partrac', max_length=10, verbose_name='Module type'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='resolution',
            field=models.FloatField(default=1000, help_text='Default resolution for raster based analysis (meters)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='tag',
            field=models.CharField(blank=True, help_text='Free tag, label or keyword to facilitate CaseStudy identification and search', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('usepre', 'Use-Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking')], max_length=10),
        ),
    ]
