# Generated by Django 2.2.2 on 2019-07-14 20:54

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0027_auto_20190714_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestudyrun',
            old_name='area_of_interest',
            new_name='domain_area',
        ),
        migrations.RenameField(
            model_name='casestudyrun',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='casestudyrun',
            name='out_ci',
        ),
        migrations.RemoveField(
            model_name='casestudyrun',
            name='out_coexist',
        ),
        migrations.AddField(
            model_name='casestudyrun',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 14, 20, 54, 26, 936135)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudyrun',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudyrun',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casestudyrun',
            name='configuration',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
