# Generated by Django 2.2.13 on 2022-04-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20211213_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivity',
            name='impact_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensitivity',
            name='recovery',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
