# Generated by Django 2.2.2 on 2019-07-15 05:15

from django.db import migrations, models
import django.db.models.deletion
import tools4msp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0028_auto_20190714_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedlabel',
            name='cltype',
            field=models.CharField(choices=[('grid', 'Grid'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('out', 'Outputs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('out', 'Outputs')], max_length=5),
        ),
        migrations.CreateModel(
            name='CaseStudyRunOutputLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('layerfile', models.FileField(blank=True, null=True, upload_to=tools4msp.models.generate_output_layer_filename)),
                ('casestudyrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputlayers', to='tools4msp.CaseStudyRun')),
                ('layer_type', models.ForeignKey(limit_choices_to={'cltype__in': ['grid', 'pre', 'env', 'use']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel')),
            ],
            options={
                'ordering': ['layer_type__cltype'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyRunOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to=tools4msp.models.generate_input_filename)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('casestudyrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='tools4msp.CaseStudyRun')),
                ('layer_type', models.ForeignKey(limit_choices_to={'cltype__in': ['grid', 'pre', 'env', 'use']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel')),
            ],
            options={
                'ordering': ['layer_type__cltype'],
            },
        ),
    ]
