# Generated by Django 2.2.2 on 2019-07-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0029_auto_20190715_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudyrunoutput',
            name='layer_type',
        ),
    ]
