# Generated by Django 2.2.13 on 2022-05-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0030_codedlabel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codedlabel',
            name='parent',
        ),
    ]
