# Generated by Django 2.2.2 on 2019-07-15 07:09

from django.db import migrations, models
import django.db.models.deletion
import tools4msp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0030_remove_casestudyrunoutput_layer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudyrunoutput',
            options={'ordering': ['output_type__cltype']},
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='casestudyrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CaseStudyRun'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tools4msp.models.generate_output_filename),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutputlayer',
            name='casestudyrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CaseStudyRun'),
        ),
    ]
