# Generated by Django 2.2.13 on 2022-05-02 20:34

from django.db import migrations, models
from treebeard.mp_tree import MP_Node

steplen = MP_Node.steplen
alphabet = MP_Node.alphabet
node_order_by = ["code"]

def update_path(apps, schema_editor):
    class Node(MP_Node):
        # may overwrite, should match new model:
        # steplen = 4
        # alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        # node_order_by = []
        pass;
    CodedLabel = apps.get_model("tools4msp","CodedLabel")
    db_alias = schema_editor.connection.alias
    
    for i, group in enumerate(CodedLabel.objects.all(), 1):
        group.path = Node._get_path(None, 1, i)
        group.save(using=db_alias)


def backwards(apps, schema_editor):
    """nothing to do"""
    pass
    

class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0031_remove_codedlabel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='codedlabel',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codedlabel',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codedlabel',
            name='path',
            field=models.CharField(default='', max_length=255),
            # preserve_default=False,
        ),
        migrations.RunPython(update_path, backwards),
        migrations.AlterField(
            model_name="codedlabel",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
