# Generated by Django 2.2.13 on 2022-05-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0032_auto_20220502_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codedlabel',
            options={},
        ),
        migrations.RemoveField(
            model_name='codedlabel',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='codedlabel',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='codedlabel',
            name='path',
        ),
    ]
