# Generated by Django 2.2.13 on 2022-05-03 07:31

from django.db import migrations, models
from treebeard.mp_tree import MP_Node

steplen = MP_Node.steplen
alphabet = MP_Node.alphabet

def update_path(apps, schema_editor):
    class Node(MP_Node):
        # may overwrite, should match new model:
        # steplen = 4
        # alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        # node_order_by = []
        pass;
    model = apps.get_model("tools4msp","Pressure")
    db_alias = schema_editor.connection.alias
    
    for i, o in enumerate(model.objects.all(), 1):
        o.path = Node._get_path(None, 1, i)
        o.save(using=db_alias)


def backwards(apps, schema_editor):
    """nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0033_auto_20220503_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressure',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressure',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pressure',
            name='path',
            field=models.CharField(default='', max_length=255),
            # preserve_default=False,
        ),
        migrations.RunPython(update_path, backwards),
    ]
