# Generated by Django 2.2.13 on 2022-05-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0034_auto_20220503_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressure",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
