# Generated by Django 2.2.13 on 2022-05-03 08:50

from django.db import migrations, models
from treebeard.mp_tree import MP_Node

steplen = MP_Node.steplen
alphabet = MP_Node.alphabet

def update_path(apps, schema_editor):
    class Node(MP_Node):
        # may overwrite, should match new model:
        # steplen = 4
        # alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        # node_order_by = []
        pass;
    model_env = apps.get_model("tools4msp","Env")
    model_use = apps.get_model("tools4msp","Use")
    db_alias = schema_editor.connection.alias
    
    for i, o in enumerate(model_env.objects.all(), 1):
        o.path = Node._get_path(None, 1, i)
        o.save(using=db_alias)
    for i, o in enumerate(model_use.objects.all(), 1):
        o.path = Node._get_path(None, 1, i)
        o.save(using=db_alias)


def backwards(apps, schema_editor):
    """nothing to do"""
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0035_auto_20220503_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codedlabel',
            options={'ordering': ['group', 'label']},
        ),
        migrations.AddField(
            model_name='env',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='env',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='env',
            name='path',
            field=models.CharField(default='', max_length=255),
            # preserve_default=False,
        ),
        migrations.AddField(
            model_name='use',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='use',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='use',
            name='path',
            field=models.CharField(default='', max_length=255),
            # preserve_default=False,
        ),
        migrations.RunPython(update_path, backwards),
    ]
