# Generated by Django 2.2.13 on 2022-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0036_auto_20220503_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name="env",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="use",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
