# Generated by Django 2.2.13 on 2022-10-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0039_clientapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='client_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools4msp.ClientApplication'),
        ),
    ]
