# Generated by Django 2.2.13 on 2022-10-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0040_casestudy_client_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='client_application',
        ),
    ]
