# Generated by Django 2.2.13 on 2022-10-20 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools4msp', '0041_remove_casestudy_client_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_application_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientapplication',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users registered by the client application', related_name='client_applications_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
