# Generated by Django 2.2.13 on 2022-10-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0042_auto_20221020_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='client_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools4msp.ClientApplication'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'hidden'), (2, 'public')], default=0),
        ),
        migrations.AddField(
            model_name='casestudyrun',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'private'), (1, 'hidden'), (2, 'public')], default=0),
        ),
    ]
