# Generated by Django 2.2.13 on 2022-12-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0044_casestudyrun_runstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivity',
            name='impact_level_class',
            field=models.CharField(blank=True, choices=[('no_pressure', 'No pressure'), ('minor', 'Minor'), ('medium', 'Medium'), ('high', 'High'), ('devastating', 'Devastating/lethal')], max_length=20, null=True),
        ),
    ]
