# Generated by Django 2.2.13 on 2023-01-06 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0047_auto_20230103_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudyrun',
            name='runerror',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudyrunlayer',
            name='casestudyrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='tools4msp.CaseStudyRun'),
        ),
    ]
