# Generated by Django 2.2.13 on 2023-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0049_auto_20230307_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudyinput',
            name='vizmode',
            field=models.IntegerField(choices=[(0, 'filtered'), (1, 'all')], default=0),
        ),
    ]
