# Generated by Django 2.2.13 on 2023-03-22 21:54

from django.db import migrations, models
import tools4msp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0053_auto_20230322_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudyinput',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='casestudylayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='casestudyruninput',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='casestudyrunlayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutputlayer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=tools4msp.models.generate_filename),
        ),
    ]
