# Generated by Django 2.2.13 on 2023-04-04 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0054_auto_20230322_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudyinput',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='casestudyinput',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='module',
            field=models.CharField(choices=[('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking'), ('pmar', 'Pressure Assessment for Marine Activities'), ('testmodule', 'Test module')], help_text='Module type. Accepted values are: cea, muc, partrac, pmar, testmodule', max_length=10, verbose_name='Module type'),
        ),
        migrations.AlterField(
            model_name='casestudyinput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac', 'pmar', 'testmodule']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudylayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac', 'pmar', 'testmodule']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyruninput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac', 'pmar', 'testmodule']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunlayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac', 'pmar', 'testmodule']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutput',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac', 'pmar', 'testmodule']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='casestudyrunoutputlayer',
            name='coded_label',
            field=models.ForeignKey(limit_choices_to={'group__in': ['casestudy', 'pre', 'usepre', 'env', 'use', 'out', 'cea', 'muc', 'partrac', 'pmar', 'testmodule']}, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.CodedLabel'),
        ),
        migrations.AlterField(
            model_name='codedlabel',
            name='group',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('usepre', 'Use-Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking'), ('pmar', 'Pressure Assessment for Marine Activities'), ('testmodule', 'Test module')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_type',
            field=models.CharField(choices=[('casestudy', 'Case Study'), ('use', 'Activity & Uses'), ('env', 'Environmental receptor'), ('pre', 'Pressure'), ('usepre', 'Use-Pressure'), ('out', 'Outputs'), ('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking'), ('pmar', 'Pressure Assessment for Marine Activities'), ('testmodule', 'Test module')], max_length=10),
        ),
    ]
