# Generated by Django 2.2.13 on 2023-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0055_auto_20230404_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudyinput',
            options={'ordering': ['coded_label__sort_order']},
        ),
        migrations.RemoveField(
            model_name='casestudyinput',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='codedlabel',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
