# Generated by Django 2.2.13 on 2023-04-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0056_auto_20230404_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='default_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tools4msp.Context'),
        ),
    ]
