# Generated by Django 2.2.13 on 2023-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0057_casestudy_default_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='module',
            field=models.CharField(choices=[('cea', 'CEA'), ('muc', 'MUC'), ('partrac', 'Particle tracking'), ('pmar', 'Pressure Assessment for Marine Activities'), ('testmodule', 'Test module'), ('geodatamaker', 'GeoData Maker')], help_text='Module type. Accepted values are: cea, muc, partrac, pmar, testmodule, geodatamaker', max_length=15, verbose_name='Module type'),
        ),
    ]
