# Generated by Django 2.2.13 on 2023-05-05 07:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0058_auto_20230415_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudyrunoutputlayer',
            name='layerinfo',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
