# Generated by Django 2.2.13 on 2024-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools4msp', '0059_casestudyrunoutputlayer_layerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msfdenv',
            options={'ordering': ['theme', 'ecosystem_component', 'broad_group'], 'verbose_name': 'MSFD environmental receptor'},
        ),
        migrations.RenameField(
            model_name='msfdenv',
            old_name='ecosystem_element',
            new_name='ecosystem_component',
        ),
        migrations.AddField(
            model_name='msfdenv',
            name='element',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='msfdenv',
            name='feature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
